### ISSUE TITLE
Edit content help texts

### ISSUE THREAD

**Issue by kristjanjansen** [kristjanjansen/trip2#151]
Mis siin on veel oluline, mis enam mitte? Mis on puudu? Katsuks jutuvada kokku tõmmata. Kas saaksime ehk tooni vähem manitsevamaks? Mitmed neist reeglitest korduvad väljade juures.

<img width="820" alt="screen shot 2015-09-04 at 15 51 03" src="https://cloud.githubusercontent.com/assets/241603/9683965/3602abce-531d-11e5-9b54-86c2901dcfba.png">
<img width="901" alt="screen shot 2015-09-04 at 15 50 57" src="https://cloud.githubusercontent.com/assets/241603/9683966/361dbb76-531d-11e5-8fb7-1aef7592da59.png">
<img width="459" alt="screen shot 2015-09-04 at 15 51 24" src="https://cloud.githubusercontent.com/assets/241603/9683967/362c5d34-531d-11e5-88b1-6d61fbb748ff.png">
<img width="869" alt="screen shot 2015-09-04 at 15 50 46" src="https://cloud.githubusercontent.com/assets/241603/9683968/362db986-531d-11e5-82df-d54b384f222e.png">
<img width="649" alt="screen shot 2015-09-04 at 15 50 35" src="https://cloud.githubusercontent.com/assets/241603/9683969/362e15d4-531d-11e5-8117-3ed91a7040d3.png">
<img width="745" alt="screen shot 2015-09-04 at 15 51 11" src="https://cloud.githubusercontent.com/assets/241603/9683970/362f6006-531d-11e5-8a16-a07e8e9bf745.png">

<img width="504" alt="screen shot 2015-09-04 at 15 51 45" src="https://cloud.githubusercontent.com/assets/241603/9683980/42851dd2-531d-11e5-9b1e-631145750930.png">
<img width="761" alt="screen shot 2015-09-04 at 15 51 53" src="https://cloud.githubusercontent.com/assets/241603/9683979/4283b82a-531d-11e5-8176-35786efab86f.png">
<img width="656" alt="screen shot 2015-09-04 at 15 52 23" src="https://cloud.githubusercontent.com/assets/241603/9683981/428586f0-531d-11e5-876c-53edfb0209a1.png">

**Comment by veigok** [comment]
See ei ole enam teemaks, sest lennupakkumisi lisab nüüd Trip.ee toimetus. Selle asemel võiks olla registreerunud kasutajatel võimalus saata vihje.

**Comment by veigok** [comment]
Näiteks mingi kastike, kuhu saab teksti lisada ja siis nupp "Saada". Samamaoodi, nagu praegu kirjutan.
